name: MirrorMaster
main: be.mc.woutwoot.MirrorMaster.MirrorMaster
version: 1.21
commands:
  mm:
    description: Main command for MirrorMaster.
    usage: /<command> [argument]
    permission: MirrorMaster.use
    permission-message: You don't have the permissions to use MirrorMaster! Tell an admin to add MirrorMaster.use